### PR TITLE
src/i2c-dev: force compiler to inline function

### PR DESCRIPTION
**Pull request by vitalogy**
Hi again,

i suppose that you wanted to have the i2c-functions inlinde into the libs?
If not, then it was a good training :+1: 

With these changes in the PR all i2c-funtions will be inlined in the object-file. I have verified this with `objdump``. For example: 

```
00001de0 <sunxidtI2CWriteReg8>:
    1de0:   e92d4800    push    {fp, lr}
    1de4:   e28db004    add fp, sp, #4
    1de8:   e24dd060    sub sp, sp, #96 ; 0x60
    1dec:   e50b0058    str r0, [fp, #-88]  ; 0xffffffa8
    1df0:   e50b105c    str r1, [fp, #-92]  ; 0xffffffa4
    1df4:   e50b2060    str r2, [fp, #-96]  ; 0xffffffa0
    1df8:   e51b3058    ldr r3, [fp, #-88]  ; 0xffffffa8
    1dfc:   e50b3008    str r3, [fp, #-8]
    1e00:   e51b305c    ldr r3, [fp, #-92]  ; 0xffffffa4
    1e04:   e50b300c    str r3, [fp, #-12]
    1e08:   e51b3060    ldr r3, [fp, #-96]  ; 0xffffffa0
    1e0c:   e50b3010    str r3, [fp, #-16]
    1e10:   e51b3010    ldr r3, [fp, #-16]
    1e14:   e6ef3073    uxtb    r3, r3
    1e18:   e54b3054    strb    r3, [fp, #-84]  ; 0xffffffac
    1e1c:   e51b3008    ldr r3, [fp, #-8]
    1e20:   e50b3014    str r3, [fp, #-20]  ; 0xffffffec
    1e24:   e3a03000    mov r3, #0
    1e28:   e54b3015    strb    r3, [fp, #-21]  ; 0xffffffeb
    1e2c:   e51b300c    ldr r3, [fp, #-12]
    1e30:   e50b301c    str r3, [fp, #-28]  ; 0xffffffe4
    1e34:   e3a03002    mov r3, #2
    1e38:   e50b3020    str r3, [fp, #-32]  ; 0xffffffe0
    1e3c:   e24b3054    sub r3, fp, #84 ; 0x54
    1e40:   e50b3024    str r3, [fp, #-36]  ; 0xffffffdc
    1e44:   e55b3015    ldrb    r3, [fp, #-21]  ; 0xffffffeb
    1e48:   e54b3030    strb    r3, [fp, #-48]  ; 0xffffffd0
    1e4c:   e51b301c    ldr r3, [fp, #-28]  ; 0xffffffe4
    1e50:   e6ef3073    uxtb    r3, r3
    1e54:   e54b302f    strb    r3, [fp, #-47]  ; 0xffffffd1
    1e58:   e51b3020    ldr r3, [fp, #-32]  ; 0xffffffe0
    1e5c:   e50b302c    str r3, [fp, #-44]  ; 0xffffffd4
    1e60:   e51b3024    ldr r3, [fp, #-36]  ; 0xffffffdc
    1e64:   e50b3028    str r3, [fp, #-40]  ; 0xffffffd8
    1e68:   e24b3030    sub r3, fp, #48 ; 0x30
    1e6c:   e1a02003    mov r2, r3
    1e70:   e3a01e72    mov r1, #1824   ; 0x720
    1e74:   e51b0014    ldr r0, [fp, #-20]  ; 0xffffffec
    1e78:   ebfffffe    bl  0 <ioctl>
    1e7c:   e1a00000    nop         ; (mov r0, r0)
    1e80:   e1a00003    mov r0, r3
    1e84:   e24bd004    sub sp, fp, #4
    1e88:   e8bd8800    pop {fp, pc}
```

I got no compile warning or error.
But I can not check if this works, because of lack of an i2c-device.

### CODE REVIEW

**Comment by vitalogy** [comment]
.. and I don't know if it is necessary to remove `return`, so I have done this only for raspberry.

**Comment by CurlyMoo** [comment]
Removing the `returns` is not wanted, as well as putting everything in the header.

**Comment by vitalogy** [comment]
I have done an other branch for inline with extern, please have a look: https://github.com/vitalogy/wiringX/tree/inline2/src

from https://gcc.gnu.org/onlinedocs/gcc/Inline.html

> This combination of inline and extern has almost the effect of a macro. The way to use it is to put a function definition in a header file with these keywords, and put another copy of the definition (lacking inline and extern) in a library file. The definition in the header file causes most calls to the function to be inlined. If any uses of the function remain, they refer to the single copy in the library.

**Comment by CurlyMoo** [comment]
Not sure if does anything usefull?

**Pull request closed without merging**
