### PR TITLE
Added MIPS CI20 Creator to supported devices list.

### PR DESCRIPTION
**Pull request by garysims**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Where you also working on that table for the CI20 for the wiringx.org frontpage?

**Comment by garysims** [comment]
Not today, I don't have the time, maybe tomorrow...

**Comment by CurlyMoo** [comment]
Fine ofc, just wanted to know if it's on your list :smile:

**Comment by CurlyMoo** [comment]
Did you find the time already? I added CI20 to pilight and it would be handy if users know how the GPIO's are mapped.

**Comment by CurlyMoo** [comment]
Sadly, i still have't heard anything from you about the documentation of your module...

**Comment by garysims** [comment]
Sorry, I have been mega busy... If someone else could just make those
document changes that would be useful for everyone I think.

All the info needed is in the .c file:

static int pinToGpio[NUM_PINS] = { 124, // wiringX # 0 - Physical pin 7 -
GPIO 1 122, // wiringX # 1 - Physical pin 11 - GPIO 2 123, // wiringX # 2 -
Physical pin 13 - GPIO 3 125, // wiringX # 3 - Physical pin 15 - GPIO 4 161,
// wiringX # 4 - Physical pin 16 - GPIO 5 162, // wiringX # 5 - Physical
pin 18 - GPIO 6 136, // wiringX # 6 - Physical pin 22 - GPIO 7 126, //
wiringX # 7 - Physical pin 3 - IC21_SDA 127, // wiringX # 8 - Physical pin
5 - I2C1_SCK 144, // wiringX # 9 - Physical pin 24 - SSI1_CE0 146, //
wiringX # 10 - Physical pin 26 - SSI1_CE1 145, // wiringX # 11 - Physical
pin 19 - SSI0_DT 142, // wiringX # 12 - Physical pin 21 - SSI0_DR 143, //
wiringX # 13 - Physical pin 23 - SSI0_CLK 163, // wiringX # 14 - Physical
pin 8 - UART0_TXD 160, // wiringX # 15 - Physical pin 10 - UART0_RXD };

**Comment by CurlyMoo** [comment]
You know that part of development is documentation :wink:

**Pull request merged**
