### PR TITLE
Removed outdated check for input capable gpios 0 and 1

### PR DESCRIPTION
**Pull request by evgmik**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
So what are you exactly fixing... Removing the check does not offer us new insight. I have a BananaPi M2 lying here, but it just doesn't work as input. We need more users to confirm your experience. Also, what OS do you use?

> I have another set of patches regarding banana pi m2 in mind. But I would like to clarify the API. What functions like waitForInterrupt, wiringXISR, wiringXValidGPIO, and wiringXGC suppose to do. I think I searched the forum and google it, but I do not see the clear link with description.

Can you describe what you want to achieve with the patches?

> I particulatly interested in what setIRQ(map) is doing. It is not implemented but yet is called in bananapiM2Setup. 

That was a bug that i already fixed.

**Comment by evgmik** [comment]
First of all, my apologizes for the PR against not updated by me branch. The fix in this particular request remove the check for gpio 0  and 1. They are input capable. We discussed it together in the forum thread [bananapiM2 gpio 0 and 1 pin mode setting limits](https://forum.pilight.org/Thread-wiringX-bananapiM2-gpio-0-and-1-pin-mode-setting-limits).

By the way on that forum, my nick is beaming.

> > I particulatly interested in what setIRQ(map) is doing. It is not implemented but yet is called in bananapiM2Setup.
> 
> That was a bug that i already fixed

Indeed, I was working with yesterday version of the code.

As for the changes in my mind, I have a fix for the input/output pin mode assignment for BananaPi M2. You can see in the following [commit](https://github.com/evgmik/wiringX/commit/a75653101ec51c32c0482202e11d38efee707055). I can make a pull request for it.

Since BananaPI M2 is in my active use, I am trying to provide as useful feedback as I can. Though, interrupts work is above my league. But I was willing to jump it. Luckily, looks like I do not need to do it.

**Comment by CurlyMoo** [comment]
I will test your code in the commit tomorrow.

**Comment by CurlyMoo** [comment]
> They are input capable. We discussed it together in the forum thread bananapiM2 gpio 0 and 1 pin mode setting limits.

You successfully tested it with your BananaPi M2, i did as well and it did not work. That means something is different. Could be the kernel or OS used. But as long as we have just two experiences we can't be sure. Maybe you can ask the BananaPi forum for closure?

**Comment by CurlyMoo** [comment]
Fixed

**Pull request closed without merging**
