### PR TITLE
Add ODROID boards support

### PR DESCRIPTION
**Pull request by bkrepo**
This commit supports ODROID-C1/C2/XU3/XU4 boards.

Signed-off-by: Brian Kim brian.kim@hardkernel.com

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Awesome! But can you please add the support into the rewrite branch. This code will become obsolete soon.

**Comment by bkrepo** [comment]
Okay, I will do. :-)

**Comment by CurlyMoo** [comment]
So what's the status?

**Comment by bkrepo** [comment]
I will pull request again to rewrite branch soon. :-)

PS. CurlyMoo, do you have ODROD boards? My boss said, we will send ODROID boards(C1, C2, XU4) for free to you as a gift if you want it.

**Comment by CurlyMoo** [comment]
No, i don't. How can i contact you?

**Comment by bkrepo** [comment]
Please send e-mail to me <brain.kim at hardkernel.com> including your shipping information.

**Comment by CurlyMoo** [comment]
Problem is that i don't have your email adres.

**Comment by bkrepo** [comment]
brian.kim@hardkernel.com

**Comment by CurlyMoo** [comment]
Mail adres doesn't work.

```
  brian.kim@hardkernel.com
    SMTP error from remote mail server after initial connection:
    host ASPMX.daum.net [180.70.93.101]: 421 4.4.5 CCRT 212.54.42.167:
    Connection refused. Server is busy(RT): retry timeout exceeded
```

**Comment by bkrepo** [comment]
I don't have any idea what is the problem. I use the e-mail address.
Anyway, please send the e-mail to my private e-mail address. <kth3321 at gmail.com>

**Comment by bkrepo** [comment]
kth3321 at gmail.com

**Pull request closed without merging**
