### PR TITLE
Add kernel version detection

### PR DESCRIPTION
**Pull request by ypflll**
For rockchip, linux kernel version below 3.10 has a pinbase of 160 and　kernel below 3.12 doesn't support "both" edge interruption. Kernel　version detection makes wiringX be compatible to all kernel version.
GPIO and interrupt are tested on a radxaboard.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Exactly how i intended it. I assume it works locally?

**Comment by ypflll** [comment]
What do you mean "locally"?
I have tested my code on radxaboard. The version detection function, I think it would work on other boards. However, the pinbase and "both" edge problem, they only involve in rockchip.

**Comment by CurlyMoo** [comment]
Just wanted to be sure :smile:

**Comment by CurlyMoo** [comment]
Can you also do the fix for the interrupt in the other modules in a new PR?

**Comment by ypflll** [comment]
I'll do it. Wait for a while~

**Pull request merged**
