### PR TITLE
Add radxaInit and fix an array overflow bug

### PR DESCRIPTION
**Pull request by ypflll**
In radxa.c, use of onboardLEDs[] overflows.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
I will merge these fixes if you also include the interrupt fix and the kernel version detection (correct GPIO numbers and interrupt edges).

**Comment by ypflll** [comment]
Actually, I have seen this in wiringX/CONTRIBUTING.md: "Make sure your pull-request contains one single commit."
So I can do several commits in one pull request?

**Comment by CurlyMoo** [comment]
By reading the link in the same item.

**Comment by ypflll** [comment]
I've read it. It says how to merge several "temporary commits" into one. However, I want to add interrupt fix, kernel version, SPI, so I should take them all as one commit, and pull one request?
This confuses me: Make a difference branch for each new feature you want to commit.

**Comment by CurlyMoo** [comment]
Ok, my advice depends on the github knowledge of the contributor. If you know how to properly do PR's then preferable do them in single commits.

Only a handfull actually reads the contribution guide (sadly).

**Pull request merged**
