### PR TITLE
Add SPI functions to documentation page

### PR DESCRIPTION
**Pull request by crazystick**

### CODE REVIEW

**Comment by linux4kix** [comment]
I am almost ready to release the new kernel including these patches. I am
trying to work on a better way to remux the pins and reallocate them to new
devices.

Jon

**Comment by CurlyMoo** [comment]
Would be great if you also still got the answer to my question how to remux pins to GPIO through memory i asked you a few weeks ago...

**Comment by crazystick** [comment]
and my 2p - still hoping for a solution to avoid the pull up resistor for Dallas 1-wire devices, and to decide if it would be reasonable to include in wiringX - I like the idea of a single library to work with any hardware device :-)

**Comment by CurlyMoo** [comment]
> and to decide if it would be reasonable to include in wiringX

Can you elaborate this?

**Comment by crazystick** [comment]
sorry - we had a conversation on IRC about getting 1-wire working on the Hummingboard, and we did succeed, but it does require more changes in the dtb files, and therefore removes a GPIO which wiringX would consider valid - which is why I'm saying it is related to the comment from @linux4kix above.

There is also a small issue that we didn't figure out how to get it to work without an external pull-up, which is not ideal from a practical POV.

I think wiringPi never had functions to deal with 1-wire devices, but I don't see a reason why wiringX should be limited by that?

**Comment by linux4kix** [comment]
I have been investigating that.  The proper way will be using device-tree
fragements to redefine the pin-mux groups for their different
functionality.  just changing them in memory won't help because the drivers
won't bind to them because they won't have a device-tree definition.  The
functionality is new and I have had to test it and start backporting
patches to our kernel.

**Comment by linux4kix** [comment]
I verified that we needed different mux settings to get that to work
without an external pullup.

**Comment by crazystick** [comment]
did you figure out what those mux settings were, the last one we tried was:

MX6QDL_PAD_GPIO_1__GPIO1_IO01 0x80000000

**Comment by CurlyMoo** [comment]
@crazystick, shouldn't we also explain what what pins can be used for SPI in the wiringX tables?

**Comment by crazystick** [comment]
Yes - and we should add the I2C labels too. I'm almost finished with PKGBUILDs for Arch Linux Arm too, so I'd like to add those to the documentation somewhere. There isn't currently a section for installation though...

**Comment by CurlyMoo** [comment]
> There isn't currently a section for installation though...

What do you mean by this?

**Comment by crazystick** [comment]
There are buttons to download the src, and the README contains instructions for compiling, and also for making a deb package, but that information is not duplicated on wiringx.org. So - should information on PKGBUILDs for Alarm be in the README or on wiringx.org?

**Comment by CurlyMoo** [comment]
Whatever you think is best. I kept the site hosted on github to allow everyone to post their ideas.

**Comment by crazystick** [comment]
Do you have some release numbering scheme? I notice that the version of the python module is 0.5, and I didn't increment it after adding the SPI functions

**Comment by CurlyMoo** [comment]
No, but i didn't make it 1.0 because interrupt support isn't implemented. So make it 0.6.

**Pull request merged**
