### PR TITLE
radxa rock board added emulate both edge triggered interrupts

### PR DESCRIPTION
**Pull request by jack-ma**
Hello, we have added  and tested both edge triggered interrupts function for radxa rock board.
https://github.com/radxa/linux-rockchip/commit/6650a736ff6a9d8043e8754d416f70d3d83ca051

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you add a kernel version detection so depending on the kernel, users still get the unsupported message?

**Comment by jack-ma** [comment]
We added emulate both edge triggered interrupts function to kernel version 3.0.36. So all versions of the kernel we released support both edge triggered interrupts function. I think don't need to judge version.

**Comment by CurlyMoo** [comment]
Ok nice.

**Comment by CurlyMoo** [comment]
Are you ok with changing the license of wiringX from GPLv3 to MPLv2?

**Comment by hipboi** [comment]
@CurlyMoo We are ok with the license. Thanks for your efforts.

**Comment by jack-ma** [comment]
We are ok with the license. Thanks for your efforts.

**Pull request merged**
