### PR TITLE
create standard debian packaging

### PR DESCRIPTION
**Pull request by Artox**
I have put in the necessary bits to generate proper debian packages (using debhelper).
Things can now easily be built by running
 dpkg-buildpackage or git-buildpackage or gbp buildpackage

I believe this obsoletes your package generation script.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What's `improper` about my own approach? That just works on all platforms.

**Comment by Artox** [comment]
https://www.debian.org/doc/debian-policy/

The standard debian-ish way works on all platforms too. And it allows integration with standard build tools, such as pbuilder, pbuildd, or the openbuildservice (where I am now building this package for wheezy, jessie and trusty for the cubox-i and hummingboard)
https://obs.gbps.io/package/show/BSP:Cubox-i/wiringX

**Comment by CurlyMoo** [comment]
I meant, building the package can be done on any platform. Even FreeBSD, because it uses plain `ar`. I agree the control, prerm, etc can be done differently, but i don't see any need for using deb tools when `ar` works fine.

**Comment by Artox** [comment]
I forgot to add a few notes on proper/improper:
the standard debian packaging is doing a lot of magic in the background, such as generating dependencies on system libraries and their versions (e.g. libc). It should also have generated the postinst on its own, but I believe it didnt because the library is not called .so.X.
Additionally stuff like stripping binaries happens, and the dpkg database gets full information on library symbols.

EDIT: I got your point on freebsd now.
With the debian packaging tools you really need to build on debian or ubuntu, or using likewise chroots (something pbuilder does e.g.)

My main issue with your .sh package builder is that in the world I can not use it with the build-service.

**Comment by CurlyMoo** [comment]
I think you are largely overestimating the debian packaging. It's nothing more then packaging in a predefined way. That's why you can simply create a debian package with `ar`.

In addition, i've created thousands of pilight package this way and never had issues.

**Comment by Artox** [comment]
Is there a way I can convince you to accept this, without finding serious flaws in your method of creating .deb?
I personally find the debian pakcaging rather convenient, and ideally the rules file stays empty, with only control, and .install to customize.

**Comment by CurlyMoo** [comment]
Please convince me :smile: You could also have done this before doing all the work.

PS. i build all my packages from FreeBSD except Windows. So, i386, amd64, mips, armv6, armv7 etc. FreeBSD is my main dev machine with all cross-compilers.

Guess how i generate the apt repo's for XBian and pilight? Indeed, with an shell script :+1: Also just works under FreeBSD, and all Linux versions.

**Comment by Artox** [comment]
Not exactly, since I need this work anyway; After all I can only build standard debian source packages (that is .dsc, .debian.tar.gz, .orig.tar.gz style) on the OBS.

Arguments why this is a good way to package:
Uses standard debian tools
 --> knows about target system, such as floating-point calling convention, architecture
can be built with distributions default cflags (such as -Werror, -O2, ....); Distros love to define those in a global manner
(those flags are ofc not used now since you hardcode a lot in cmake)
cross-compiles naturally: the debian tools know what to pass to cmake, or configure to make that work
easy maintenance: debian/*.install files when new files are added, or renamed, debian/rules when build process changes, debian/changelog to tell users whats new and set version
self-contained in debian subfolder

I dont think I have any additional arguments.

**Comment by CurlyMoo** [comment]
What i am open too is using cpack to generate the deb package. I was too lazy when initially starting this repository. By using cmake and cpack we can generate deb, rpm, tar,gz etc. natively with cmake.

In respect to your true comments, i've updated the whole thing to use native cmake and cpack deb and rpm generation.

**Comment by Artox** [comment]
This PR is really outdated now, time to close it.
I might look into using cpack to generate the debian source package I need (wonder if that works)

**Pull request closed without merging**
